import os
import numpy as np
import pandas as pd

# Paths
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))

PROCESSED_FILE = os.path.join(
    PROJECT_ROOT, "data", "processed", "unified_demand_repository.csv"
)
CURATED_DIR = os.path.join(PROJECT_ROOT, "data", "curated")
os.makedirs(CURATED_DIR, exist_ok=True)


def build_features():
    print("⏳ Building time-series and demand features...")

    if not os.path.exists(PROCESSED_FILE):
        raise FileNotFoundError(f"Missing input file: {PROCESSED_FILE}")

    df = pd.read_csv(PROCESSED_FILE)
    df["date"] = pd.to_datetime(df["date"])

    # Sort data for time-series feature calculation
    df = df.sort_values(by=["sku_id", "date"]).reset_index(drop=True)

    # 1. Calendar & Time Features
    df["day_of_week"] = df["date"].dt.dayofweek
    df["month"] = df["date"].dt.month
    df["is_weekend"] = df["day_of_week"].apply(lambda x: 1 if x >= 5 else 0)

    # 2. Lag Features (Historical demand signals)
    df["sales_lag_1"] = df.groupby("sku_id")["units_sold"].shift(1)
    df["sales_lag_7"] = df.groupby("sku_id")["units_sold"].shift(7)
    df["sales_lag_14"] = df.groupby("sku_id")["units_sold"].shift(14)

    # 3. Rolling Moving Averages & Volatility
    df["rolling_mean_7"] = (
        df.groupby("sku_id")["units_sold"]
        .transform(lambda x: x.shift(1).rolling(window=7).mean())
    )
    df["rolling_std_7"] = (
        df.groupby("sku_id")["units_sold"]
        .transform(lambda x: x.shift(1).rolling(window=7).std())
    )

    # Fill NaN values generated by lag operations
    df = df.bfill().ffill()

    # Save to Curated Zone
    output_path = os.path.join(CURATED_DIR, "demand_features.csv")
    df.to_csv(output_path, index=False)
    print(f"✅ Feature engineering complete! Curated dataset saved to: {output_path}")


if __name__ == "__main__":
    build_features()